### ISSUE TITLE
Environment plots should show noon to noon

### ISSUE THREAD

**Issue by martinjohndyer** [warwick-one-metre/dashboard#13]
When browsing the environment data it would be more useful to see data over the whole night.

**Comment by pchote** [comment]
Fixed by 4e450fe40714d9724e4eede2805a92edfb2084f2.

**Comment by martinjohndyer** [comment]
Thanks. One slight nitpick - after midnight you still get a page created for the new day, but it's going to be blank for 12 hours.

**Comment by pchote** [comment]
Fixed by 1b9de88d572efe93cceb55fb65cd4e2ad4b642fe.
